---
# loops through installing flatpak packages

- name: Check Flatpak is installed
  ansible.builtin.dnf:
    name: flatpak
    state: present
  become: true

- name: Install Flatpak packages
  ansible.builtin.flatpak:
    name: 
      - com.github.tchx84.Flatseal
      - com.spotify.Client
      - com.discordapp.Discord
      - com.mojang.Minecraft
      - io.github.realmazharhussain.GdmSettings
    state: present
  become: true
